language: python

sudo: false

cache:
    directories:
        - $HOME/.cache/pip

python:
  - "3.6"

install:
  - pip install --upgrade pip setuptools pipenv
  - pipenv install --dev --pre
  
script:
  - script: pipenv run ./scripts/run-build.sh
