language: python

sudo: false

cache:
    directories:
        - $HOME/.cache/pip

python:
  - "3.6"

install:
  - pip install --upgrade pip setuptools pipenv
  - pipenv install --dev --pre
  
script:
  - pipenv run python -m coverage -m pytest tests

jobs:
  include:
    # Prechecks that we want to run first.
    - stage: main
      script: 'pipenv run black --check src tests setup.py'
    - script: 'pipenv run coverage run --branch -m pytest tests/ && pipenv run coverage report --show-missing --fail-under=100'
